### ISSUE TITLE
keymap not working

### ISSUE THREAD

**Issue by sunnykb** [colinta/SublimeMoveText#11]
I am using Sublime 3 on Mac El Capitan, installed the MoveText package using Package Control.
The keymap does not work, do I have to store the example.sublime-keymap in any perticular directory?

Thanks

Sunil

**Comment by colinta** [comment]
You can edit your keyboard shortcuts from preferences, then copy and paste the example key bindings.

**Comment by sunnykb** [comment]
That was fast:

Here is my user preference file but error out with Unexpected character.

Appreciate your insight.


{
"color_scheme": "Packages/Color Scheme - Default/Solarized (Light).tmTheme",
"fade_fold_buttons": false,
"ignored_packages":
[
"CSS",
"Vintage"
]

[
{ "keys": ["super+ctrl+left"], "command": "move_text_left" },
{ "keys": ["super+ctrl+right"], "command": "move_text_right" },
{ "keys": ["super+ctrl+up"], "command": "move_text_up" },
{ "keys": ["super+ctrl+down"], "command": "move_text_down" }
]
}

**Comment by colinta** [comment]
Yeah not that one - you were in the right place, but there are two config files, one for key bindings and another for settings/preferences.

(I'm away from my computer otherwise is screen shot it)

**Comment by sunnykb** [comment]
Got it, that did help. Appreciate your responses.
Thanks a lot for the package and help.

**Comment by colinta** [comment]
Happy to help!

If that resolves things, can you close the issue? :-)

**Comment by sunnykb** [comment]
Issue resolved, thanks for prompt responses.
