### ISSUE TITLE
move_up mangles line order with multiple cursors

### ISSUE THREAD

**Issue by AllanLRH** [colinta/SublimeMoveText#12]
I think it's nicely demonstrated in the gif below, but I'll try to answer any further questions if they arise.
The gif is captured on a retina screen, so it'll most likely display sharper if it's opened in its own tab :)
![sublime_multicursor_drag_problem](https://user-images.githubusercontent.com/2641327/35444198-047007e4-02ae-11e8-9df1-87c3d5d1d5f1.gif)

**Comment by colinta** [comment]
I've been meaning to fix this for a while, and it turned out to be surprisingly easy to fix!  Try version 2.0.4 when it's available on Package Control (I just pushed it to github, takes a while to register the new version).
