### ISSUE TITLE
keymapping not working

### ISSUE THREAD

**Issue by shirha** [colinta/SublimeMoveText#13]
I installed your example user key mappings but nothing happens when I use winkey+ctrl+left or right arrows after column selection. I'm sorry, but I don't know what else to try. 

Here are my "Default (Windows).sublime-keymap" 
[
    { "keys": ["super+ctrl+left"], "command": "move_text_left" },
    { "keys": ["super+ctrl+right"], "command": "move_text_right" },
    { "keys": ["super+ctrl+up"], "command": "move_text_up" },
    { "keys": ["super+ctrl+down"], "command": "move_text_down" }
]

and "Package Control.sublime-settings" files
{
	"bootstrapped": true,
	"in_process_packages":
	[
	],
	"installed_packages":
	[
		"MoveText",
		"Package Control"
	]
}

**Comment by colinta** [comment]
Did you try other keymaps, maybe the windows key can't be used in this way, I'm not sure.  For instance you could try (assuming 'ctrl+alt+left' isn't a system command):

```
{ "keys": ["ctrl+alt+left"], "command": "move_text_left" }
```

**Comment by colinta** [comment]
Also, when you paste JSON or code, always use triple backticks for code formatting 
` ``` `
` your code `
` ``` `

**Comment by shirha** [comment]
You were right. Winkey is not supported! All combinations of arrow keys are used up. I used ctrl+alt+w,s,a,d and it worked perfectly! Thanks for your quick suggestion.
