### ISSUE TITLE
Move up and down seams not working correctly?

### ISSUE THREAD

**Issue by 9840380** [colinta/SublimeMoveText#16]
When i moving left or right it seams to work normal reversing characters. When i move up and down it not reversing text itself it moving text sides not reverse same part of text...

Should it be so?

![Screen Recording 2023-04-19 at 22 51 14 copy copy](https://user-images.githubusercontent.com/33433075/233185342-4c3fc397-1348-427e-974f-f5967853e53e.gif)

**Comment by colinta** [comment]
Thanks for the video! This is working as expected, as far as I can tell. 

I don't quite understand your explanation above, but it sounds like you expected it to swap the text; this is not how the feature was designed to work. 

I _do_ have a plug-in for that, though- https://github.com/colinta/SublimeTransposeCharacter

But this one works by swapping _two selections_, it doesn't automatically swap text the way you are (I think) hoping. 

Sorry, hope this helps!
